# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth', '0002_auto_20180814_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dockers',
            fields=[
                ('id', models.CharField(default=b'473d333517304051a8d9465a4e55f1b3', max_length=32, primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(protocol='ipv4')),
                ('name', models.CharField(max_length=256, null=True)),
                ('status', models.CharField(max_length=16, null=True)),
                ('description', models.TextField(null=True)),
                ('metadata', models.TextField(default='{}')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.Users')),
            ],
            options={
                'db_table': 'dockers',
            },
        ),
    ]
