# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='id',
            field=models.CharField(default=b'241a0ca3732640378506305f31cc37d0', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='id',
            field=models.CharField(default=b'abfac17248cc45f8bf2d9ce6e54b98a5', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.CharField(default=b'b813e52d59bd4adf95e516225fd96b47', max_length=32, primary_key=True, serialize=False),
        ),
    ]
