# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-01 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ports',
            fields=[
                ('id', models.CharField(default=b'0720af8e0ff34db6be6262549ac94ca9', max_length=32, primary_key=True, serialize=False)),
                ('port', models.IntegerField(null=True)),
                ('is_free', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ports',
            },
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.CharField(default=b'32d06eb33300470480367f60d554c92c', max_length=32, primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(protocol='ipv4')),
                ('hostname', models.CharField(max_length=256, null=True)),
                ('salt', models.CharField(max_length=16)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=16, null=True)),
                ('description', models.CharField(max_length=256, null=True)),
                ('version', models.CharField(max_length=32, null=True)),
                ('cpu_number', models.IntegerField(null=True)),
                ('memory_size', models.IntegerField(null=True)),
                ('container_number', models.IntegerField(null=True)),
                ('metadata', models.TextField(default='{}')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.Users')),
            ],
            options={
                'db_table': 'servers',
            },
        ),
        migrations.AddField(
            model_name='ports',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.Servers'),
        ),
    ]
