# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ports',
            name='id',
            field=models.CharField(default=b'a2fdaddc6114410e8112665263b9779a', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servers',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='servers',
            name='id',
            field=models.CharField(default=b'0a2d4dea2e644d9dae825dc9e1a88922', max_length=32, primary_key=True, serialize=False),
        ),
    ]
